[package]
name = "ccc"
version = "0.1.0"
edition = "2021"

[dependencies]
# inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
#     "llvm14-0",
# ] }
# rand = "0.8.5"
# smallvec = "1.9.0"
# itertools = "0.10.3"
# once_cell = "1.13.1"
